// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AV2_Biblioteca_Final.Model.Models;

public partial class Autores
{
    public int AutorId { get; set; }

    public string Nome { get; set; }

    public DateTime? DataNascimento { get; set; }

    public string Nacionalidade { get; set; }

    public virtual ICollection<Livros> Livros { get; set; } = new List<Livros>();
}