USE [master]
GO

/****** Object:  Database [BibliotecaDB]    Script Date: 28/11/2023 17:00:57 ******/
CREATE DATABASE [BibliotecaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BibliotecaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BibliotecaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BibliotecaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BibliotecaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BibliotecaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BibliotecaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BibliotecaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BibliotecaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BibliotecaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BibliotecaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BibliotecaDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BibliotecaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BibliotecaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BibliotecaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BibliotecaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BibliotecaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BibliotecaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BibliotecaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BibliotecaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BibliotecaDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BibliotecaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BibliotecaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BibliotecaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BibliotecaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BibliotecaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BibliotecaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BibliotecaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BibliotecaDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BibliotecaDB] SET  MULTI_USER 
GO

ALTER DATABASE [BibliotecaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BibliotecaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BibliotecaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BibliotecaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BibliotecaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BibliotecaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BibliotecaDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [BibliotecaDB] SET  READ_WRITE 
GO


